name: CI Docker Build & Push

on:
  push:
    branches:
      - lab-docker

jobs:
  docker:
    runs-on: ubuntu-latest

    environment: dev

    env:
      IMAGE_NAME: ci-html-demo
      IMAGE_TAG: latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      
      - name: Push de l’image Docker
        run: |
          echo "dev.secrets.DOCKERHUB_USERNAME ${{ dev.secrets.DOCKERHUB_USERNAME }}" 

      - name: Connexion à Docker Hub
        run: echo "${{ dev.secrets.DOCKERHUB_TOKEN }}" | docker login \
             -u "${{ dev.secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build de l’image Docker
        run: |
          docker build -t ${{ dev.secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push de l’image Docker
        run: |
          docker push ${{ dev.secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
